### ISSUE TITLE
2.4.0 + master: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [ionelmc/sphinx-py3doc-enhanced-theme#15]
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
Using --randomly-seed=2165419781
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-py3doc-enhanced-theme-2.4.0, configfile: setup.cfg, testpaths: tests
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, Faker-8.4.0, cov-2.12.1, randomly-3.8.0, pyfakefs-4.5.0, hypothesis-6.13.14
collected 1 item

tests/reference/foobar.rst F                                                                                                                                         [100%]

================================================================================= FAILURES =================================================================================
___________________________________________________________________________ [doctest] foobar.rst ___________________________________________________________________________
001 :mod:`foobar` --- Boring lorem ipsum
002 =====================================
003
004 .. module:: foobar
005     :synopsis: Some other fake module to test rendering
006
007
008 .. sourcecode:: pycon
009
010     >>> def fib(n):
UNEXPECTED EXCEPTION: SyntaxError('unexpected EOF while parsing', ('<doctest foobar.rst[0]>', 1, 12, 'def fib(n):\n'))
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest foobar.rst[0]>", line 1
    def fib(n):
              ^
SyntaxError: unexpected EOF while parsing
/home/tkloczko/rpmbuild/BUILD/sphinx-py3doc-enhanced-theme-2.4.0/tests/reference/foobar.rst:10: UnexpectedException
========================================================================= short test summary info ==========================================================================
FAILED tests/reference/foobar.rst::foobar.rst
============================================================================ 1 failed in 0.14s =============================================================================
```

**Comment by ionelmc** [comment]
Mkay, fixed now. Do you need a release or what's going on over there?

**Comment by kloczek** [comment]
Just tested that patch and all looks good now :)
```console
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-py3doc-enhanced-theme-2.4.0, configfile: setup.cfg, testpaths: tests
plugins: pytest_check-1.0.1, forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, toolbox-0.5, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, hypothesis-6.14.4, Faker-8.10.3, xprocess-0.18.1, black-0.3.12, checkdocs-2.7.1, anyio-3.3.0
collected 1 item

tests/reference/foobar.rst .                                                                                                                                         [100%]

============================================================================ 1 passed in 0.13s =============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```
Thank you.
(no I don't need that ASAP new release as I have now integrated that patch in my build process so if you've been planning to make new release later it will be no problem)

Thank you very much and feel free to close this ticket :)
